theme:jekell-theme-cayman
title:Welcome to the upload page for entry into the current Dunchurch PS event
description: Dunchurch Photographic Society (DPS) is looking tocover costs by running regular photography events. We invite subscribers to our U-tube channel to make a donation and upload a maximum of 2 pictures to a self-judged event.